name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Crossroads
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.3.0
      with:
        version: 'v0.2.7'

    - name: Build Crossroads
      run: |
        rojo build . -o crossroads.rbxl
        rojo build . -o crossroads.rbxlx

    - name: 'Upload to Release'
      run: |
        gh release list --limit 1 --jq '[].tagName' >> $LAST_TAG
        echo $LAST_TAG
      env:
        GITHUB_TOKEN: ${{ github.token }}